language: php
os: linux
php:
  - 7.1
  - 7.2
  - 7.3

install:
  # Install composer packages, will also trigger dump-autoload
  - composer self-update
  - composer install --no-interaction --ignore-platform-reqs

  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - php php-coveralls.phar --version

before_script:
  - composer require friendsofphp/php-cs-fixer
  - composer require phpunit/phpunit ^7
  - mkdir -p build/logs
  - ls -al

script:
  - composer validate
  - phpunit --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix . --verbose --diff --dry-run

after_success:
  - travis_retry php php-coveralls.phar -v

cache:
  directories:
    - $HOME/.php-cs-fixer

matrix:
  fast_finish: true
