language: php
os: linux
sudo: false
services:
  - memcached

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - echo yes | pecl install -f apcu
  - phpenv config-add ./tests/php.ini

install:
  # Install composer packages, will also trigger dump-autoload
  - composer validate
  - composer require --no-interaction --ignore-platform-reqs "phpunit/phpunit:^7" "friendsofphp/php-cs-fixer"
  - composer install --no-interaction --ignore-platform-reqs --no-suggest

  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - php php-coveralls.phar --version

before_script:
  - mkdir -p build/logs
  - ls -al

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix --config .php_cs --verbose --diff --dry-run

after_success:
  - travis_retry php php-coveralls.phar -v

cache:
  directories:
    - $HOME/.php-cs-fixer

matrix:
  fast_finish: true
